# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1397, 975)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #353535;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_widget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.left_widget)
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tree_widget = QtWidgets.QTreeWidget(parent=self.left_widget)
        self.tree_widget.setStyleSheet("QTreeWidget {\n"
"    background-color: #252525;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    outline: none;\n"
"}\n"
"QTreeWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #444444;\n"
"}\n"
"QTreeWidget::item:selected {\n"
"    background-color: #2a82da;\n"
"    color: white;\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    background-color: #3a3a3a;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #454545;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: 1px solid #555555;\n"
"    font-weight: bold;\n"
"}")
        self.tree_widget.setHeaderHidden(False)
        self.tree_widget.setObjectName("tree_widget")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_widget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_2.addWidget(self.tree_widget)
        self.background = QtWidgets.QPushButton(parent=self.left_widget)
        self.background.setStyleSheet("QPushButton {\n"
"    background-color: #454545;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    padding: 8px 12px;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    min-height: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"    border: 1px solid #666666;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2a82da;\n"
"    border: 1px solid #1a72ca;\n"
"}")
        self.background.setObjectName("background")
        self.verticalLayout_2.addWidget(self.background)
        self.export_layout = QtWidgets.QHBoxLayout()
        self.export_layout.setSpacing(10)
        self.export_layout.setObjectName("export_layout")
        self.export_csv_btn = QtWidgets.QPushButton(parent=self.left_widget)
        self.export_csv_btn.setStyleSheet("QPushButton {\n"
"    background-color: #454545;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    padding: 8px 12px;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    min-height: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"    border: 1px solid #666666;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2a82da;\n"
"    border: 1px solid #1a72ca;\n"
"}")
        self.export_csv_btn.setObjectName("export_csv_btn")
        self.export_layout.addWidget(self.export_csv_btn)
        self.export_txt_btn = QtWidgets.QPushButton(parent=self.left_widget)
        self.export_txt_btn.setStyleSheet("QPushButton {\n"
"    background-color: #454545;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    padding: 8px 12px;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    min-height: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"    border: 1px solid #666666;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2a82da;\n"
"    border: 1px solid #1a72ca;\n"
"}")
        self.export_txt_btn.setObjectName("export_txt_btn")
        self.export_layout.addWidget(self.export_txt_btn)
        self.verticalLayout_2.addLayout(self.export_layout)
        self.horizontalLayout.addWidget(self.left_widget)
        self.right_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_widget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.right_widget)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.player_widget = QtWidgets.QWidget(parent=self.right_widget)
        self.player_widget.setObjectName("player_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.player_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.player_widget)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: #252525;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    padding: 5px;\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid #2a82da;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #454545;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #757575;\n"
"    border-radius: 2px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #858585;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.control_layout = QtWidgets.QHBoxLayout()
        self.control_layout.setSpacing(10)
        self.control_layout.setObjectName("control_layout")
        self.progress_slider = QtWidgets.QSlider(parent=self.player_widget)
        self.progress_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #555555;\n"
"    height: 6px;\n"
"    background: #454545;\n"
"    border-radius: 2px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #757575;\n"
"    border: 1px solid #555555;\n"
"    width: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 3px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #858585;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #2a82da;\n"
"    border-radius: 2px;\n"
"}")
        self.progress_slider.setMinimum(0)
        self.progress_slider.setMaximum(100)
        self.progress_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.control_layout.addWidget(self.progress_slider)
        self.time_label = QtWidgets.QLabel(parent=self.player_widget)
        self.time_label.setStyleSheet("QLabel {\n"
"    background-color: #454545;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    padding: 6px;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"}")
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setProperty("fixedWidth", 100)
        self.time_label.setObjectName("time_label")
        self.control_layout.addWidget(self.time_label)
        self.verticalLayout_3.addLayout(self.control_layout)
        self.verticalLayout.addWidget(self.player_widget)
        self.label_4 = QtWidgets.QLabel(parent=self.right_widget)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.info_widget = QtWidgets.QWidget(parent=self.right_widget)
        self.info_widget.setObjectName("info_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.info_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_label = QtWidgets.QLabel(parent=self.info_widget)
        self.title_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    background-color: #454545;\n"
"    padding: 10px;\n"
"    border: 1px solid #555555;\n"
"}")
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_4.addWidget(self.title_label)
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.info_widget)
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    background-color: #252525;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    padding: 5px;\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid #2a82da;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #454545;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #757575;\n"
"    border-radius: 2px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #858585;\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_4.addWidget(self.textEdit_2)
        self.update_btn = QtWidgets.QPushButton(parent=self.info_widget)
        self.update_btn.setStyleSheet("QPushButton {\n"
"    background-color: #454545;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    padding: 8px 12px;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    min-height: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"    border: 1px solid #666666;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2a82da;\n"
"    border: 1px solid #1a72ca;\n"
"}")
        self.update_btn.setObjectName("update_btn")
        self.verticalLayout_4.addWidget(self.update_btn)
        self.complexity_group = QtWidgets.QGroupBox(parent=self.info_widget)
        self.complexity_group.setStyleSheet("QGroupBox {\n"
"    background-color: #353535;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    margin-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    color: white;\n"
"    background-color: #454545;\n"
"    padding: 5px 10px;\n"
"    border: 1px solid #555555;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"}")
        self.complexity_group.setObjectName("complexity_group")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.complexity_group)
        self.verticalLayout_5.setContentsMargins(5, 15, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.time = QtWidgets.QLabel(parent=self.complexity_group)
        self.time.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    background-color: #454545;\n"
"    padding: 8px;\n"
"    border: 1px solid #555555;\n"
"}")
        self.time.setObjectName("time")
        self.verticalLayout_5.addWidget(self.time)
        self.verticalLayout_4.addWidget(self.complexity_group)
        self.verticalLayout.addWidget(self.info_widget)
        self.horizontalLayout.addWidget(self.right_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("QStatusBar {\n"
"    background-color: #454545;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 11px;\n"
"    border-top: 1px solid #555555;\n"
"}")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPlay = QtGui.QAction(parent=MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause = QtGui.QAction(parent=MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtGui.QAction(parent=MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        self.actionHelp.setObjectName("actionHelp")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qt Algorithms Visualizer"))
        self.label.setText(_translate("MainWindow", "Библиотека алгоритмов:"))
        self.tree_widget.headerItem().setText(0, _translate("MainWindow", "Алгоритмы"))
        __sortingEnabled = self.tree_widget.isSortingEnabled()
        self.tree_widget.setSortingEnabled(False)
        self.tree_widget.topLevelItem(0).setText(0, _translate("MainWindow", "Сортировки"))
        self.tree_widget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Сортировка пузырьком"))
        self.tree_widget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Сортировка подсчетом"))
        self.tree_widget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Быстрая сортировка"))
        self.tree_widget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Сортировка слиянием"))
        self.tree_widget.topLevelItem(1).setText(0, _translate("MainWindow", "Алгоритмы поиска"))
        self.tree_widget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Бинарный поиск"))
        self.tree_widget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Поиск в ширину(BFS)"))
        self.tree_widget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Поиск в глубину(DFS)"))
        self.tree_widget.topLevelItem(2).setText(0, _translate("MainWindow", "Теория чисел"))
        self.tree_widget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Решето Эратосфена"))
        self.tree_widget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Алгоритм Евклида"))
        self.tree_widget.topLevelItem(3).setText(0, _translate("MainWindow", "Динамическое программирование"))
        self.tree_widget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Последовательность Фибоначчи"))
        self.tree_widget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Задача о рюкзаке"))
        self.tree_widget.topLevelItem(4).setText(0, _translate("MainWindow", "Графы"))
        self.tree_widget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Алгоритм Дейкстры"))
        self.tree_widget.setSortingEnabled(__sortingEnabled)
        self.background.setText(_translate("MainWindow", "Сменить обои"))
        self.export_csv_btn.setText(_translate("MainWindow", "Экспорт информации в CSV"))
        self.export_txt_btn.setText(_translate("MainWindow", "Экспорт кодов в TXT"))
        self.label_2.setText(_translate("MainWindow", "Визуализация алгоритма:"))
        self.time_label.setText(_translate("MainWindow", "00:00 / 00:00"))
        self.label_4.setText(_translate("MainWindow", "Информация об алгоритме:"))
        self.title_label.setText(_translate("MainWindow", "Выберите категорию или алгоритм"))
        self.update_btn.setText(_translate("MainWindow", "Изменить информацию"))
        self.complexity_group.setTitle(_translate("MainWindow", "Асимптотика"))
        self.time.setText(_translate("MainWindow", "Временная сложность: "))
        self.actionPlay.setText(_translate("MainWindow", "▶ Воспроизведение"))
        self.actionPause.setText(_translate("MainWindow", "⏸ Пауза"))
        self.actionStop.setText(_translate("MainWindow", "⏹ Стоп"))
        self.actionSettings.setText(_translate("MainWindow", "⚙ Настройки"))
        self.actionHelp.setText(_translate("MainWindow", "❓ Справка"))
